Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Weba1\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\Desktop\Weba1\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\Desktop\Weba1\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\Desktop\Weba1\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\user\Desktop\Weba1\app.py", line 76, in home
    return 1/0#render_template("homepage1.html")
ZeroDivisionError: division by zero
